site_name: Transport Scotland Data Standards

theme:
  name: material

markdown_extensions:
  - abbr
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed

extra_css:
  - stylesheets/palette.css